#!groovy

// Build pipeline for the devnet environment
// This pipeline provides a centralised point to control the build of the various components that make up the devnet deployment
// The pipeline expects to be called from other pipelines which will update the parameters of the repo they come from

pipeline {
    agent {
        label 'hamlet-latest'
    }
    options {
        timestamps ()
        buildDiscarder(
            logRotator(
                daysToKeepStr: '14'
            )
        )
        disableConcurrentBuilds()
        durabilityHint('PERFORMANCE_OPTIMIZED')
        parallelsAlwaysFailFast()
        checkoutToSubdirectory('deploy')
    }

    environment {
        properties_file = "/var/opt/properties/devnet.properties"
        GITHUB_CREDENTIALS = credentials('github')

        //Set Initial CD Environment
        ENVIRONMENT="services"
    }

    parameters {
        string(
            name: 'branchref_shareddbchannel',
            defaultValue: 'master',
            description: 'The commit to use for the deploy'
        )

        booleanParam(
            name: 'force_shareddbchannel',
            defaultValue: false,
            description: 'Force build of intergov components'
        )
    }

    stages {
        // Shared DB Channel

        stage('Setup') {
            steps {
                dir('shared-db-channel/') {
                    script {
                        def repoSharedDbChannel = checkout(
                            [
                                $class: 'GitSCM',
                                branches: [[name: "${params.branchref_shareddbchannel}" ]],
                                userRemoteConfigs: [[
                                    credentialsId: 'github',
                                    url: 'https://github.com/trustbridge/shared-db-channel'
                                ]]
                            ]
                        )
                        env.gitcommit_shareddbchannel = repoSharedDbChannel.GIT_COMMIT
                    }
                }
            }
        }

        stage('Build - Shared DB Channel') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_shareddbchannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_shareddbchannel}"
                        }
                        branch 'master'
                    }
                }
            }

            steps {
                echo "GIT_COMMIT is ${env.branchref_shareddbchannel}"

                dir('shared-db-channel/') {
                    sh '''#!/bin/bash
                        if [[ -d "${HOME}/.nodenv" ]]; then
                            export PATH="$HOME/.nodenv/bin:$PATH"
                            eval "$(nodenv init - )"
                            nodenv install 12.16.1 || true
                            nodenv shell 12.16.1
                        fi
                        npm install serverless@1.67.3 serverless-python-requirements@5.1.0 serverless-wsgi@1.7.4
                        export PATH="$( npm bin ):$PATH"

                        sls package --package dist/channel_api --config "../deploy/shared-db-channel/channel_api/lambda/serverless.yml"
                        sls package --package dist/utilities --config "../deploy/shared-db-channel/utilities/lambda/serverless.yml"
                    '''
                }
            }

            post {
                success {
                    dir('shared-db-channel/') {
                        archiveArtifacts artifacts: 'dist/channel_api/channel_api.zip', fingerprint: true
                        archiveArtifacts artifacts: 'dist/utilities/shared-db-channel-utilities.zip', fingerprint: true
                    }

                    slackSend (
                        message: "Build Completed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n Shared DB Channel Lambda Build Completed",
                        channel: "#igl-automatic-messages",
                        color: "#50C878"
                    )
                }

                failure {
                    slackSend (
                        message: "Build Failed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n Shared DB Channel Lambda Build Completed",
                        channel: "#igl-automatic-messages",
                        color: "#B22222"
                    )
                }
            }
        }

        stage('Artefact - Shared DB Channel - channel_api') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_shareddbchannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_shareddbchannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'sharedchannel-api-imp-c1,sharedchannel-api-imp-c2'
                segment = 'channel'
                image_format = 'lambda'
                BUILD_SRC_DIR = 'shared-db-channel/'
            }

            steps {

                dir('shared-db-channel/') {
                    sh '''
                        cp dist/channel_api/channel_api.zip dist/lambda.zip
                    '''
                }

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_shareddbchannel}"
                )

                build job: '../cote-services/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_shareddbchannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

        }

        stage('Artefact - Shared DB Channel - Utilities') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_shareddbchannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_shareddbchannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'sharedchannel-utilities'
                segment = 'channel'
                image_format = 'lambda'
                BUILD_SRC_DIR = 'shared-db-channel/'
            }

            steps {

                dir('shared-db-channel/') {
                    sh '''
                        cp dist/utilities/shared-db-channel-utilities.zip dist/lambda.zip
                    '''
                }

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_shareddbchannel}"
                )

                build job: '../cote-services/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_shareddbchannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

        }

        stage('Artefact - Shared DB Channel - channel_apigw') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_shareddbchannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_shareddbchannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'sharedchannel-api-c1,sharedchannel-api-c2'
                segment = 'channel'
                image_format = 'swagger'
                BUILD_SRC_DIR = 'shared-db-channel/'

                // App specific
                IGL_DEFAULT_SQS_USE_SSL = 'false'
                IGL_DEFAULT_SQS_HOST = 'sqs.local'
                IGL_DEFAULT_SQS_PORT = '443'
                IGL_DEFAULT_SQS_REGION = 'ap-southeast-2'

                IGL_DEFAULT_S3_USE_SSL = 'false'
                IGL_DEFAULT_S3_HOST = 's3.local'
                IGL_DEFAULT_S3_PORT = '443'
                IGL_DEFAULT_S3_REGION = 'ap-southeast-2'

            }

            steps {


                dir('shared-db-channel/') {
                    sh '''
                    pip install -r requirements.txt
                    python ./manage.py generate_swagger

                    cat swagger.yaml | python -c 'import sys, yaml, json; y=yaml.safe_load(sys.stdin.read()); print(json.dumps(y))' > swagger.json
                    mv swagger.json swagger-extended-base.json
                    zip -j swagger.zip swagger-extended-base.json
                    cp swagger.zip dist/swagger.zip
                    '''
                }

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_shareddbchannel}"
                )

                build job: '../cote-services/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_shareddbchannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

        }

        stage('Build - Processor') {
             when {
                anyOf {
                    equals expected: true, actual: params.force_shareddbchannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_shareddbchannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'sharedchannel-delivery-c1,sharedchannel-spreader-c1,sharedchannel-observer-c1,sharedchannel-delivery-c2,sharedchannel-spreader-c2,sharedchannel-observer-c2'
                segment = 'channel'
                image_format = 'docker'
                BUILD_PATH = 'shared-db-channel/'
                DOCKER_CONTEXT_DIR = 'shared-db-channel'
                BUILD_SRC_DIR = ''
                DOCKER_FILE = 'shared-db-channel/docker/api.Dockerfile'
            }

            steps {

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_shareddbchannel}"
                )

                build job: '../cote-services/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_shareddbchannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

            post {
                success {
                    slackSend (
                        message: "Build Completed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n Shared Channel Processer Completed",
                        channel: "#igl-automatic-messages",
                        color: "#50C878"
                    )
                }

                failure {
                    slackSend (
                        message: "Build Failed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n Shared Channel Processor Failed",
                        channel: "#igl-automatic-messages",
                        color: "#B22222"
                    )
                }
            }
        }
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}


void uploadImageToRegistry( properties_file, deployment_unit, image_format, git_commit )   {

    script {
        env['deployment_unit'] = "${deployment_unit}"
        env['image_format'] = "${image_format}"
        env['unit_git_commit'] = "${git_commit}"
    }

    // Product Setup
    script {
        def contextProperties = readProperties interpolate: true, file: "${properties_file}" ;
        contextProperties.each{ k, v -> env["${k}"] ="${v}" }
    }

    sh '''#!/bin/bash
    ${AUTOMATION_BASE_DIR}/setContext.sh || exit $?
    '''

    script {
        def contextProperties = readProperties interpolate: true, file: "${WORKSPACE}/context.properties";
        contextProperties.each{ k, v -> env["${k}"] ="${v}" }
    }

    sh '''#!/bin/bash
    ${AUTOMATION_DIR}/manageImages.sh -g "${unit_git_commit}" -u "${deployment_unit}" -f "${image_format}"  || exit $?
    '''

    script {
        def contextProperties = readProperties interpolate: true, file: "${WORKSPACE}/context.properties";
        contextProperties.each{ k, v -> env["${k}"] ="${v}" }
    }

}
