service: shared-db-channel

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  individually: true
  include:
    - '!./**'
    - './api/**'
    - './migrations/**'
    - './manage.py'
  exclude:
    - '**'

custom:
  wsgi:
    app: api.lambda.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: 'non-linux'
    invalidateCaches: true
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-southeast-2

functions:
  channel_api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
