#!groovy

// Build pipeline for the devnet environment
// This pipeline provides a centralised point to control the build of the various components that make up the devnet deployment
// The pipeline expects to be called from other pipelines which will update the parameters of the repo they come from

pipeline {
    agent {
        label 'hamlet-latest'
    }
    options {
        timestamps ()
        buildDiscarder(
            logRotator(
                daysToKeepStr: '14'
            )
        )
        disableConcurrentBuilds()
        durabilityHint('PERFORMANCE_OPTIMIZED')
        parallelsAlwaysFailFast()
        checkoutToSubdirectory('deploy')
    }

    environment {
        properties_file = "/var/opt/properties/devnet.properties"
        GITHUB_CREDENTIALS = credentials('github')
    }

    parameters {
        string(
            name: 'branchref_apichannel',
            defaultValue: 'master',
            description: 'The commit to use for the deploy'
        )

        booleanParam(
            name: 'force_apichannel',
            defaultValue: false,
            description: 'Force build of intergov components'
        )
    }

    stages {
        // Shared DB Channel

        stage('Setup') {
            steps {
                dir('api-channel/') {
                    script {
                        def repoSharedAPIChannel = checkout(
                            [
                                $class: 'GitSCM',
                                branches: [[name: "${params.branchref_apichannel}" ]],
                                userRemoteConfigs: [[
                                    credentialsId: 'github',
                                    url: 'https://github.com/trustbridge/api-channel'
                                ]]
                            ]
                        )
                        env.gitcommit_apichannel = repoSharedAPIChannel.GIT_COMMIT
                    }
                }
            }
        }

        stage('Build - API Channel') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_apichannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_apichannel}"
                        }
                        branch 'master'
                    }
                }
            }

            steps {
                echo "GIT_COMMIT is ${env.branchref_apichannel}"

                dir('api-channel/') {
                    sh '''#!/bin/bash
                        if [[ -d "${HOME}/.nodenv" ]]; then
                            export PATH="$HOME/.nodenv/bin:$PATH"
                            eval "$(nodenv init - )"
                            nodenv install 12.16.1 || true
                            nodenv shell 12.16.1
                        fi
                        npm install serverless@1.67.3 serverless-python-requirements@5.1.0 serverless-wsgi@1.7.4
                        export PATH="$( npm bin ):$PATH"

                        sls package --package dist/channel_api --config "../deploy/api-channel/channel_api/lambda/serverless.yml"
                    '''
                }
            }

            post {
                success {
                    dir('api-channel/') {
                        archiveArtifacts artifacts: 'dist/channel_api/channel_api.zip', fingerprint: true
                    }

                    slackSend (
                        message: "Build Completed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n API Channel Lambda Build Completed",
                        channel: "#igl-automatic-messages",
                        color: "#50C878"
                    )
                }

                failure {
                    slackSend (
                        message: "Build Failed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n API Channel Lambda Build Completed",
                        channel: "#igl-automatic-messages",
                        color: "#B22222"
                    )
                }
            }
        }

        stage('Artefact - API Channel - channel_api') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_apichannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_apichannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'apichannel-api-imp'
                segment = 'channel'
                image_format = 'lambda'
                BUILD_SRC_DIR = 'api-channel/'
            }

            steps {

                dir('api-channel/') {
                    sh '''
                        cp dist/channel_api/channel_api.zip dist/lambda.zip
                    '''
                }

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_apichannel}"
                )

                build job: '../cote-c1/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_apichannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

        }

        stage('Artefact - API Channel - channel_apigw') {
            when {
                anyOf {
                    equals expected: true, actual: params.force_apichannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_apichannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'apichannel-api'
                segment = 'channel'
                image_format = 'swagger'
                BUILD_SRC_DIR = 'api-channel/'

            }

            steps {

                // Use Proxy spec for API GW
                dir('api-channel/') {
                    sh '''
                    cp ../deploy/api-channel/channel_api/apigw/swagger.json ./swagger-extended-base.json
                    zip -j swagger.zip swagger-extended-base.json
                    cp swagger.zip dist/swagger.zip
                    '''
                }

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_apichannel}"
                )

                build job: '../cote-c1/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_apichannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

        }

        stage('Build - Processor') {
             when {
                anyOf {
                    equals expected: true, actual: params.force_apichannel
                    allOf {
                        not {
                            equals expected: 'master', actual: "${params.branchref_apichannel}"
                        }
                        branch 'master'
                    }
                }
            }

            environment {
                //hamlet deployment variables
                deployment_units = 'apichannel-delivery,apichannel-spreader'
                segment = 'channel'
                image_format = 'docker'
                BUILD_PATH = 'api-channel/'
                DOCKER_CONTEXT_DIR = 'api-channel'
                BUILD_SRC_DIR = ''
                DOCKER_FILE = 'api-channel/docker/api.Dockerfile'
            }

            steps {

                uploadImageToRegistry(
                    "${env.properties_file}",
                    "${env.deployment_units.split(',')[0]}",
                    "${env.image_format}",
                    "${env.gitcommit_apichannel}"
                )

                build job: '../cote-c1/deploy', wait: false, parameters: [
                        extendedChoice(name: 'DEPLOYMENT_UNITS', value: "${env.deployment_units}"),
                        string(name: 'GIT_COMMIT', value: "${env.gitcommit_apichannel}"),
                        booleanParam(name: 'AUTODEPLOY', value: true),
                        string(name: 'IMAGE_FORMATS', value: "${env.image_format}"),
                        string(name: 'SEGMENT', value: "${env.segment}")
                ]
            }

            post {
                success {
                    slackSend (
                        message: "Build Completed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n API Channel Processer Completed",
                        channel: "#igl-automatic-messages",
                        color: "#50C878"
                    )
                }

                failure {
                    slackSend (
                        message: "Build Failed - ${BUILD_DISPLAY_NAME} (<${BUILD_URL}|Open>)\n API Channel Processor Failed",
                        channel: "#igl-automatic-messages",
                        color: "#B22222"
                    )
                }
            }
        }
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}


void uploadImageToRegistry( properties_file, deployment_unit, image_format, git_commit )   {

    script {
        env['deployment_unit'] = "${deployment_unit}"
        env['image_format'] = "${image_format}"
        env['unit_git_commit'] = "${git_commit}"
    }

    // Product Setup
    script {
        def contextProperties = readProperties interpolate: true, file: "${properties_file}" ;
        contextProperties.each{ k, v -> env["${k}"] ="${v}" }
    }

    sh '''#!/bin/bash
    ${AUTOMATION_BASE_DIR}/setContext.sh || exit $?
    '''

    script {
        def contextProperties = readProperties interpolate: true, file: "${WORKSPACE}/context.properties";
        contextProperties.each{ k, v -> env["${k}"] ="${v}" }
    }

    sh '''#!/bin/bash
    ${AUTOMATION_DIR}/manageImages.sh -g "${unit_git_commit}" -u "${deployment_unit}" -f "${image_format}"  || exit $?
    '''

    script {
        def contextProperties = readProperties interpolate: true, file: "${WORKSPACE}/context.properties";
        contextProperties.each{ k, v -> env["${k}"] ="${v}" }
    }

}
